---
- name: Hosts or populate inventory into hosts file
  blockinfile:
    dest: /etc/hosts
    block: |-
      {% for item in groups['os-cluster'] %}
      {{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ item }}.{{ domain_name }} {{ item }}
      {% endfor %}
    state: present
    create: yes
    backup: yes
    marker: "# Ansible inventory hosts {mark}"
  when: populate_inventory_to_hosts_file
